name: ssh my machine
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: ssh my machine
      env:
        MY_VAR: Hi there! My name is
      run: |
        sshpass -p 19980418@Pwd ssh root@120.48.122.125 -o "StrictHostKeyChecking no" touch /opt/123
